/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dataset-management/create-version': RouteRecordInfo<'/dataset-management/create-version', '/dataset-management/create-version', Record<never, never>, Record<never, never>>,
    '/dataset-management/dataset-detail': RouteRecordInfo<'/dataset-management/dataset-detail', '/dataset-management/dataset-detail', Record<never, never>, Record<never, never>>,
    '/dataset-management/dataset-list': RouteRecordInfo<'/dataset-management/dataset-list', '/dataset-management/dataset-list', Record<never, never>, Record<never, never>>,
    '/inference-scheduling/auto-scaling': RouteRecordInfo<'/inference-scheduling/auto-scaling', '/inference-scheduling/auto-scaling', Record<never, never>, Record<never, never>>,
    '/inference-scheduling/intelligent-scheduling': RouteRecordInfo<'/inference-scheduling/intelligent-scheduling', '/inference-scheduling/intelligent-scheduling', Record<never, never>, Record<never, never>>,
    '/inference-scheduling/resource-pool': RouteRecordInfo<'/inference-scheduling/resource-pool', '/inference-scheduling/resource-pool', Record<never, never>, Record<never, never>>,
    '/model-deployment/deployment-detail': RouteRecordInfo<'/model-deployment/deployment-detail', '/model-deployment/deployment-detail', Record<never, never>, Record<never, never>>,
    '/model-deployment/one-click-deploy': RouteRecordInfo<'/model-deployment/one-click-deploy', '/model-deployment/one-click-deploy', Record<never, never>, Record<never, never>>,
    '/model-deployment/performance-monitoring': RouteRecordInfo<'/model-deployment/performance-monitoring', '/model-deployment/performance-monitoring', Record<never, never>, Record<never, never>>,
    '/model-deployment/performance-testing': RouteRecordInfo<'/model-deployment/performance-testing', '/model-deployment/performance-testing', Record<never, never>, Record<never, never>>,
    '/model-deployment/pod-logs': RouteRecordInfo<'/model-deployment/pod-logs', '/model-deployment/pod-logs', Record<never, never>, Record<never, never>>,
    '/model-deployment/service-list': RouteRecordInfo<'/model-deployment/service-list', '/model-deployment/service-list', Record<never, never>, Record<never, never>>,
    '/model-evaluation/create-task': RouteRecordInfo<'/model-evaluation/create-task', '/model-evaluation/create-task', Record<never, never>, Record<never, never>>,
    '/model-evaluation/evaluation-results': RouteRecordInfo<'/model-evaluation/evaluation-results', '/model-evaluation/evaluation-results', Record<never, never>, Record<never, never>>,
    '/model-evaluation/task-list': RouteRecordInfo<'/model-evaluation/task-list', '/model-evaluation/task-list', Record<never, never>, Record<never, never>>,
    '/model-finetune/create-task': RouteRecordInfo<'/model-finetune/create-task', '/model-finetune/create-task', Record<never, never>, Record<never, never>>,
    '/model-finetune/task-detail': RouteRecordInfo<'/model-finetune/task-detail', '/model-finetune/task-detail', Record<never, never>, Record<never, never>>,
    '/model-finetune/task-list': RouteRecordInfo<'/model-finetune/task-list', '/model-finetune/task-list', Record<never, never>, Record<never, never>>,
    '/model-marketplace/api-docs': RouteRecordInfo<'/model-marketplace/api-docs', '/model-marketplace/api-docs', Record<never, never>, Record<never, never>>,
    '/model-marketplace/model-detail': RouteRecordInfo<'/model-marketplace/model-detail', '/model-marketplace/model-detail', Record<never, never>, Record<never, never>>,
    '/model-marketplace/model-list': RouteRecordInfo<'/model-marketplace/model-list', '/model-marketplace/model-list', Record<never, never>, Record<never, never>>,
    '/model-marketplace/playground': RouteRecordInfo<'/model-marketplace/playground', '/model-marketplace/playground', Record<never, never>, Record<never, never>>,
    '/model-operations/alert-management': RouteRecordInfo<'/model-operations/alert-management', '/model-operations/alert-management', Record<never, never>, Record<never, never>>,
    '/model-operations/audit-log': RouteRecordInfo<'/model-operations/audit-log', '/model-operations/audit-log', Record<never, never>, Record<never, never>>,
    '/model-operations/invocation-log': RouteRecordInfo<'/model-operations/invocation-log', '/model-operations/invocation-log', Record<never, never>, Record<never, never>>,
    '/model-operations/organization-management': RouteRecordInfo<'/model-operations/organization-management', '/model-operations/organization-management', Record<never, never>, Record<never, never>>,
    '/model-operations/resource-permission': RouteRecordInfo<'/model-operations/resource-permission', '/model-operations/resource-permission', Record<never, never>, Record<never, never>>,
    '/model-operations/user-role': RouteRecordInfo<'/model-operations/user-role', '/model-operations/user-role', Record<never, never>, Record<never, never>>,
    '/service-monitoring/operational-report': RouteRecordInfo<'/service-monitoring/operational-report', '/service-monitoring/operational-report', Record<never, never>, Record<never, never>>,
    '/service-monitoring/service-monitoring': RouteRecordInfo<'/service-monitoring/service-monitoring', '/service-monitoring/service-monitoring', Record<never, never>, Record<never, never>>,
  }
}
